require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'RelatedDigitalExample' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'RNRate', :path => '../node_modules/react-native-rate'

  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
