# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RelatedDigitalNotificationService' do
  pod 'react-native-related-digital', :path => '../node_modules/react-native-related-digital'
  
  use_native_modules!
end

target 'RelatedDigitalNotificationContent' do
  use_native_modules!
  
  pod 'Euromsg', '>= 2.0.0'
end

# Post Install processing for RelatedDigitalNotificationService causing errors
def notification_service_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end

target 'reactSDKTest' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    notification_service_post_install(installer)
    
    # Fix for iOS Simulator - ensure all pods support simulator architectures
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        # Remove any arm64 exclusions for simulator to support Apple Silicon Macs
        if config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]']
          excluded_archs = config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'].split(' ')
          excluded_archs.delete('arm64')
          if excluded_archs.empty?
            config.build_settings.delete('EXCLUDED_ARCHS[sdk=iphonesimulator*]')
          else
            config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = excluded_archs.join(' ')
          end
        end
        # Enable building for active architecture only in debug
        if config.name == 'Debug'
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        end
      end
    end
  end
end

